# Generated by Django 4.2.3 on 2023-07-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0032_alter_blocklistsubmission_reason_url_null_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='max_version',
        ),
        migrations.RemoveField(
            model_name='block',
            name='min_version',
        ),
        migrations.RemoveField(
            model_name='blocklistsubmission',
            name='max_version',
        ),
        migrations.RemoveField(
            model_name='blocklistsubmission',
            name='min_version',
        ),
        migrations.AlterField(
            model_name='blocklistsubmission',
            name='disable_addon',
            field=models.BooleanField(
                default=None,
                help_text='Should the add-on be disabled after the submission is published. '
                'Unknown means only disable if no other signed versions exist.',
                null=True,
            ),
        ),
    ]
