# Generated by Django 3.2.16 on 2022-11-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_emailuserrestriction_email_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.CharField(default='', editable=False, max_length=45, null=True),
        ),
    ]
